export const NOTIFICATION_RECIEVED = 'NOTIFICATION_RECIEVED';
export const NOTIFICATION_DISMISSED = 'NOTIFICATION_DISMISSED';
export const NOTIFICATION_UPDATED = 'NOTIFICATION_UPDATED';
export const NOTIFICATIONS_START_FLOW = 'NOTIFICATIONS_START_FLOW';
export const NOTIFICATION_FLOW_TYPE_CONTACT_FULFILLMENT = 'NOTIFICATION_FLOW_TYPE_CONTACT_FULFILLMENT';



